### PR TITLE
Fix trimmed zeros in transaction encoding

### LINKED ISSUE #91: Cannot encode transactions when `to` address starts with zeros

### PR DESCRIPTION
**Pull request by alisinabh**
We don't need to trim zeros if we:

1. Make sure the transaction data will always be hex encoded starting with '0x' AND
2. Pass them as integers to `ExRLP.encode/1`

Using the existing `trim_leading/1` on all transaction values is dangerous as it can alter the transaction. For example a transaction `data` starting with one or more zero(s) or transaction `to` address which start with one or more zero(s) is perfectly fine. Since ExRLP already handles integers, we need to pass these transaction parameters as integers so we get the correct RLP encoding.

Closes #91

### CODE REVIEW

File: lib/ethers/transaction.ex [hunk 1]
```diff
@@ -257,22 +257,12 @@ defmodule Ethers.Transaction do
...
-        bin
-        |> Utils.hex_decode!()
-        |> trim_leading()
-
-      l when is_list(l) ->
-        convert_to_binary(l)
-
-      nil ->
-        ""
+  defp hex_decode("0x" <> _ = bin) do
```
Comment (wchenNL) [inline lib/ethers/transaction.ex:260]: I think it missed two other matching clauses here for the case of empty `input` - eg native token transfer.

```
 defp hex_decode(nil), do: ""

 defp hex_decode(item), do: item
```

Saw this error

```
** (FunctionClauseError) no function clause matching in Ethers.Transaction.hex_decode/1    
    
    The following arguments were given to Ethers.Transaction.hex_decode/1:
    
        # 1
        ""
    
    Attempted function clauses (showing 2 out of 2):
    
        defp hex_decode(<<"0x", _::binary>> = bin)
        defp hex_decode(list) when is_list(list)
    
    (ethers 0.3.0) lib/ethers/transaction.ex:264: Ethers.Transaction.hex_decode/1
    (ethers 0.3.0) lib/ethers/transaction.ex:211: Ethers.Transaction.to_rlp_list/1
    (ethers 0.3.0) lib/ethers/transaction.ex:106: Ethers.Transaction.encode/1
    (ethers 0.3.0) lib/ethers/signer/local.ex:36: Ethers.Signer.Local.sign_transaction/2
    (ethers 0.3.0) lib/ethers.ex:759: Ethers.use_signer/3
    (ethers 0.3.0) lib/ethers.ex:333: Ethers.send/2
    iex:1: (file)

```

Comment (alisinabh) [reply lib/ethers/transaction.ex:263]: Fixed in d0b451c

**Review by wchenNL — APPROVED** [review]
🚢 LGTM
